### PR TITLE
feat: support `HeadBucket` request

### PR DESCRIPTION
**Pull request by DDtKey**

### CODE REVIEW

**Comment by paolobarbolini** [comment]
Thanks! I'll make a release in the following days

**Comment by DDtKey** [comment]
Cool! But looks like I forgot to apply `cargo fmt` 😬

**Comment by paolobarbolini** [comment]
Ah. I'll make a commit before releasing to fix it.

**Comment by DDtKey** [comment]
Thanks!

**Comment by DDtKey** [comment]
It probably makes sense to mention it in `README` as well 🤔

**Comment by paolobarbolini** [comment]
Usually those kind of things would be caught by CI but I was too fast at merging. Also GitHub not running CI for first time contributors isn't helping.

**Comment by paolobarbolini** [comment]
Released as 0.4.1

**Pull request merged**
